#write a programme that displays diamond pattern
print("                 *                        ")
print("              ******                      ")
print("             ********                     ")
print("           ***********                    ")
print("            *********                     ")
print("             *******                      ")
print("              *****                       ")
print("               ***                        ")
print("                *                         ")